### ISSUE TITLE
custom metric cpu_percent status

### ISSUE THREAD

**Issue by scaviator** [oxtopus/skeleton-htmengine-app#19]
Hello,

I ran the the "python create_cpu_percent_model.py" script to create the model; however, my model status is 2.

```
> mysql: [Warning] Using a password on the command line interface can be insecure.
> +----------------------------------+-------------+---------------------------+--------+
> | uid                              | name        | description               | status |
> +----------------------------------+-------------+---------------------------+--------+
> | 771aa5ae606743df848e5817b68ffdbd | cpu_percent | Custom metric cpu_percent |      2 |
> +----------------------------------+-------------+---------------------------+--------+
```

What does a status 2 mean?  

I'm running the "python send_cpu.py" script in the background.  I see metric_value data, but everything else is NULL.

```
> mysql: [Warning] Using a password on the command line interface can be insecure.
> +----------------------------------+-------+---------------------+--------------+-------------------+---------------+---------------+-----------------------------+
> | uid                              | rowid | timestamp           | metric_value | raw_anomaly_score | anomaly_score | display_value | multi_step_best_predictions |
> +----------------------------------+-------+---------------------+--------------+-------------------+---------------+---------------+-----------------------------+
> | 771aa5ae606743df848e5817b68ffdbd |   314 | 2018-07-12 06:26:10 |         52.2 |              NULL |          NULL |          NULL | NULL                        |
> | 771aa5ae606743df848e5817b68ffdbd |   313 | 2018-07-12 06:26:05 |         52.1 |              NULL |          NULL |          NULL | NULL                        |
> | 771aa5ae606743df848e5817b68ffdbd |   312 | 2018-07-12 06:26:00 |         52.5 |              NULL |          NULL |          NULL | NULL                        |
> | 771aa5ae606743df848e5817b68ffdbd |   311 | 2018-07-12 06:25:55 |         52.2 |              NULL |          NULL |          NULL | NULL                        |
> | 771aa5ae606743df848e5817b68ffdbd |   310 | 2018-07-12 06:25:50 |         52.2 |              NULL |          NULL |          NULL | NULL                        |
> +----------------------------------+-------+---------------------+--------------+-------------------+---------------+---------------+-----------------------------+
```

**Comment by scaviator** [comment]
I found the meaning of the status in the code.  

```
From:
 ~/.local/lib/python2.7/site-packages/htmengine/repository/queries.py
 
 # This state is used when a model creation command has been sent to the
 # engine but hasn't been processed yet.
 CREATE_PENDING = 0b0010 # 2
```

Any idea why the engine is not processing the model creation request?

**Comment by scaviator** [comment]
I checked the **model_scheduler.log** file  and I see the following errors:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/afang/.local/lib/python2.7/site-packages/htmengine/model_swapper/model_runner.py", line 41, in <module>
    from nupic.frameworks.opf.modelfactory import ModelFactory
ImportError: No module named modelfactory
```

It looks like this is another refactoring issue.  Does anybody know what **modelfactory** was renamed to in nupic 1.0.6 ?

**Comment by scaviator** [comment]
Found it. 

Needed to replace modelfactory with model_factory.  The model creation request is now getting processed:

```
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------------------------------+-------------+---------------------------+--------+
| uid                              | name        | description               | status |
+----------------------------------+-------------+---------------------------+--------+
| dd0a52a0ea1843cca859706815f8a877 | cpu_percent | Custom metric cpu_percent |      1 |
+----------------------------------+-------------+---------------------------+--------+
```

The anomaly_scores are getting populated as well.

```
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------------------------------+-------+---------------------+--------------+--------------------+---------------+---------------+-----------------------------+
| uid                              | rowid | timestamp           | metric_value | raw_anomaly_score  | anomaly_score | display_value | multi_step_best_predictions |
+----------------------------------+-------+---------------------+--------------+--------------------+---------------+---------------+-----------------------------+
| dd0a52a0ea1843cca859706815f8a877 |    44 | 2018-07-14 05:26:15 |         11.3 |              0.125 |             0 |             0 | null                        |
| dd0a52a0ea1843cca859706815f8a877 |    43 | 2018-07-14 05:26:10 |         12.1 |  0.025000000372529 |             0 |             0 | null                        |
| dd0a52a0ea1843cca859706815f8a877 |    42 | 2018-07-14 05:26:05 |         10.2 | 0.0750000029802322 |             0 |             0 | null                        |
| dd0a52a0ea1843cca859706815f8a877 |    41 | 2018-07-14 05:26:00 |         10.3 | 0.0750000029802322 |             0 |             0 | null                        |
| dd0a52a0ea1843cca859706815f8a877 |    40 | 2018-07-14 05:25:55 |         11.3 |                  0 |             0 |             0 | null                        |
+----------------------------------+-------+---------------------+--------------+--------------------+---------------+---------------+-----------------------------+
```
